### ISSUE TITLE
Lib not compatible with latest major version of @azure/msal-browser

### ISSUE THREAD

**Issue by Gaelik-git** [joelmeiller/cypress-msal-login#12]
When trying to upgrade @azure/msal-browser to v3.0.2 I get the following error

```
Error: Webpack Compilation Error
Module not found: Error: Package path ./dist/cache/BrowserCacheManager is not exported from package [WORKDIR]/node_modules/@azure/msal-browser (see exports field in [WORKDIR]/node_modules/@azure/msal-browser/package.json)

Module not found: Error: Package path ./dist/config/Configuration is not exported from package [WORKDIR]/node_modules/@azure/msal-browser (see exports field in [WORKDIR]/node_modules/@azure/msal-browser/package.json)

Module not found: Error: Package path ./dist/crypto/CryptoOps is not exported from package [WORKDIR]/node_modules/@azure/msal-browser (see exports field in [WORKDIR]/node_modules/@azure/msal-browser/package.json)

Module not found: Error: Package path ./dist/packageMetadata is not exported from package [WORKDIR]/node_modules/@azure/msal-browser (see exports field in [WORKDIR]/node_modules/@azure/msal-browser/package.json)

Module not found: Error: Package path ./dist/response/ResponseHandler is not exported from package [WORKDIR]/node_modules/@azure/msal-common (see exports field in [WORKDIR]/node_modules/@azure/msal-common/package.json)
    at handle ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:441:32)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:505:17
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Cache.js:122:37)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:490:11
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at [HOME]/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:736:33
```

Is it an issue on my side ? Is there a plan on supporting this new version ?
Thanks for your help

**Comment by joelmeiller** [comment]
@Gaelik-git Updates to @azure/msal-browser@3.0.2 are coming soon. I started working on the V2 but it's not ready yet.

**Comment by joelmeiller** [comment]
@Gaelik-git Release is published. Please test on your side. It was trickier then expected due to the new restrictions with the exports settings in the package.json. Thus, I had to copy the code of the azure libraries to use it. For my Cypress tests it worked smoothly again.

**Comment by baptiste-le-m** [comment]
Sorry for the late response, the new version works with the latest @azure/msal-browser
Thanks for the good work
