### ISSUE TITLE
ClientAuthError 

### ISSUE THREAD

**Issue by pazernh** [joelmeiller/cypress-msal-login#2]
Hi, 

after obtaining token library is making to get requests and then throws error: 

client_info_empty_error: The client info was empty. Please review the trace to determine the root cause.
node_modules/@azure/msal-common/dist/error/AuthError.js:27:1
`
  25 |         var _this = this;
  26 |         var errorString = errorMessage ? errorCode + ": " + errorMessage : errorCode;
> 27 |         _this = _super.call(this, errorString) || this;
     | ^
  28 |         Object.setPrototypeOf(_this, AuthError.prototype);
  29 |         _this.errorCode = errorCode || Constants.EMPTY_STRING;
  30 |         _this.errorMessage = errorMessage || "";`

stack trace: 
`at ClientAuthError.AuthError [as constructor] (webpack:///./node_modules/@azure/msal-common/dist/error/AuthError.js:27:1)
    at new ClientAuthError (webpack:///./node_modules/@azure/msal-common/dist/error/ClientAuthError.js:198:1)
    at Function../node_modules/@azure/msal-common/dist/error/ClientAuthError.js.ClientAuthError.createClientInfoEmptyError (webpack:///./node_modules/@azure/msal-common/dist/error/ClientAuthError.js:215:1)
    at ResponseHandler../node_modules/@azure/msal-common/dist/response/ResponseHandler.js.ResponseHandler.generateAccountEntity (webpack:///./node_modules/@azure/msal-common/dist/response/ResponseHandler.js:209:34)
    at ResponseHandler../node_modules/@azure/msal-common/dist/response/ResponseHandler.js.ResponseHandler.generateCacheRecord (webpack:///./node_modules/@azure/msal-common/dist/response/ResponseHandler.js:160:1)
    at ResponseHandler.eval (webpack:///./node_modules/@azure/msal-common/dist/response/ResponseHandler.js:102:1)
    at step (webpack:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:75:1)
    at Object.eval [as next] (webpack:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:56:45)
    at eval (webpack:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:49:1)
        at new Promise (<anonymous>)
From previous event:
    at getRet (http://localhost:60245/__cypress/runner/cypress_runner.js:153093:21)
From previous event:
    at Context.thenFn (http://localhost:60245/__cypress/runner/cypress_runner.js:153111:64)
    at Context.then (http://localhost:60245/__cypress/runner/cypress_runner.js:153563:22)
    at Context.<anonymous> (http://localhost:60245/__cypress/runner/cypress_runner.js:169833:24)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:168527:18)
From previous event:
    at runCommand (http://localhost:60245/__cypress/runner/cypress_runner.js:168506:11)
    at next (http://localhost:60245/__cypress/runner/cypress_runner.js:168649:17)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:168678:19)
From previous event:
    at next (http://localhost:60245/__cypress/runner/cypress_runner.js:168649:37)
From previous event:
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:182790:80)
From previous event:
    at Object.run (http://localhost:60245/__cypress/runner/cypress_runner.js:182785:24)
    at Object.run (http://localhost:60245/__cypress/runner/cypress_runner.js:168703:18)
    at $Cy.cy.<computed> [as msalLogin] (http://localhost:60245/__cypress/runner/cypress_runner.js:169873:20)
    at Context.runnable.fn (http://localhost:60245/__cypress/runner/cypress_runner.js:170097:24)
    at callFn (http://localhost:60245/__cypress/runner/cypress_runner.js:122959:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:60245/__cypress/runner/cypress_runner.js:122946:8)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:176627:31)
From previous event:
    at Object.onRunnableRun (http://localhost:60245/__cypress/runner/cypress_runner.js:176612:20)
    at $Cypress.action (http://localhost:60245/__cypress/runner/cypress_runner.js:166178:29)
    at Test.Runnable.run (http://localhost:60245/__cypress/runner/cypress_runner.js:174346:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:60245/__cypress/runner/cypress_runner.js:123618:11)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:123744:13)
    at next (http://localhost:60245/__cypress/runner/cypress_runner.js:123527:15)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:123537:8)
    at next (http://localhost:60245/__cypress/runner/cypress_runner.js:123439:15)
    at <unknown> (http://localhost:60245/__cypress/runner/cypress_runner.js:123505:6)
    at timeslice (http://localhost:60245/__cypress/runner/cypress_runner.js:117431:28)
`

have you got such issue?

**Comment by joelmeiller** [comment]
As this issue is stale and I have released an updated version I close this issue.
